//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebnaya_praktika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_of_lading
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill_of_lading()
        {
            this.Card = new HashSet<Card>();
        }
    
        public int ID_bill { get; set; }
        public System.DateTime Date { get; set; }
        public string Name_of_inv { get; set; }
        public int Number_of_product { get; set; }
        public string Empl_full_name { get; set; }
        public string Empl_post { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card { get; set; }
    }
}
