//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebnaya_praktika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ID_inv { get; set; }
        public string Type_of_inv { get; set; }
        public string Name { get; set; }
        public int ID_card { get; set; }
        public int ID_warehouse { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
