//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebnaya_praktika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt_invoice()
        {
            this.Card = new HashSet<Card>();
        }
    
        public int ID_rec_invoice { get; set; }
        public System.DateTime Date_rec { get; set; }
        public string Name_of_inv_rec { get; set; }
        public int Number_of_product_rec { get; set; }
        public string Empl_full_name_rec { get; set; }
        public string Empl_post_rec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card { get; set; }
    }
}
