//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebnaya_praktika.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseEntities : DbContext
    {
        private static WarehouseEntities _context;
        public WarehouseEntities()
            : base("name=WarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static WarehouseEntities GetContext()
        {
            if (_context == null)
                _context = new WarehouseEntities();
            return _context;
        }
        public virtual DbSet<Bill_of_lading> Bill_of_lading { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Receipt_invoice> Receipt_invoice { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
